version: "3.2"
services:
  db:
    image: postgres:10.12-alpine
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  web:
    build: .
    env_file: ./.env
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command:
      - ./run.sh
