version: '3'

services:
  web:
    build:
      dockerfile: Dockerfile  
      context: .
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/flowscan_dev
    links:
      - db
  
  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - /postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:            