name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: flowscan_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MIX_ENV: test
      DATABASE_URL: postgres://postgres:123456@localhost:5432/flowscan_test
      SECRET_KEY: OpbwAq6eNHzYDY4at9/FXE4B8hjYxMRirZAx2wa82Ae5SMlDfp5voToRukMdlyvl
      PHX_DASHBOARD_USERNAME: greg
      PHX_DASHBOARD_PASSWORD: egg
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: 23.1
          elixir-version: 1.12.2
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
      - run: mix credo --strict
